
# NumPy学习心得
description: 隔壁老王|1303024845@qq.com

## NumPy快速处理数据
## 函数库的导入

In [1]:
import numpy as np

## 创建数组
* 使用array函数创建数组

In [11]:
import numpy as np
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

* 创建多维数组

In [12]:
import numpy as np
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 使用shape属性

    注意：数组在进行shape操作时一定要确保是可以shape的

* 利用shape读取数组结构

In [14]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.shape)
print(b.shape)

(5,)
(3, 3)


显然,shape中的元素个数就是维数

* 利用shape改变轴的大小

In [16]:
import numpy as np
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b.shape = 1, 9
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

    如果出现一个原本3行4列的c矩阵，经过`c.shape = 4, 3`，**注意这不是转置**，数组元素在内存中位置没有改变

* 当某个轴的元素为-1时，将根据数组元素的个数自动计算此轴的长度

In [17]:
b.shape = 3, -1
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* 用reshape方法创建新数组，原数组shape不变

In [18]:
import numpy as np
a = np.array([1, 2, 3, 4])
d = a.reshape((2, 2))
print(d)
print(a)

[[1 2]
 [3 4]]
[1 2 3 4]


## dtype

* 可以利用dtype来获得元素类型，也可以通过dtype参数在创建时制定元素类型

In [20]:
import numpy as np
a = np.array([[1, 2, 3, 4],[4, 5, 6, 7], [7, 8, 9, 10]], dtype=np.float)
a.dtype

dtype('float64')

## 用arange函数创建数组

arange类似python中的range，包含开始值、终值和步长，同样左闭右开

In [21]:
import numpy as np
a = np.arange(0, 1, 0.1)
a

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

    其他还有很多创建数组的方法，可以参考： <http://old.sebug.net/paper/books/scipydoc/numpy_intro.html>

## 存取元素

* 使用下标范围存取元素  
    数组元素通过下标存取方法和python中slice相同,但是数组通过下标范围获取的新的数组是原始数组的一个视图。它与原始数组共享同一块数据空间就是说一个变另一个也变。

* 使用整数序列存取元素

In [22]:
import numpy as np
x = np.arange(10, 1, -1)
y = x[[2, 2, -2, 1]]
y

array([8, 8, 3, 9])

    使用整数序列作为下标获得的数组**不和原始数组共享数据空间**

    其他还有很多存取元素的方法，可以参考： <http://old.sebug.net/paper/books/scipydoc/numpy_intro.html>

## 多维数组

* 创建一个二维加法数组

In [23]:
import numpy as np
add_2 = np.arange(0, 60, 10).reshape(-1, 1) + np.arange(0, 6)
add_2

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

    纵轴的每个元素都和横轴的每个元素求和，就得到图中所示的数组add_2

In [24]:
import numpy as np
add_2 = np.arange(0, 60, 10).reshape(-1, 1) + np.arange(0, 6)
print(add_2[0, 3 : 5])
print(add_2[:, 2])    # 冒号不可省略
print(add_2[3 : 5, 1 : 4])

[3 4]
[ 2 12 22 32 42 52]
[[31 32 33]
 [41 42 43]]


    从以上的代码可以了解如何存取二维数组中的元素

## 结构数组

* 在C语言中用struct关键字定义结构体，在NumPy中可以按如下方法定义：

In [26]:
import numpy as np
PersonalType = np.dtype({'names' : ['name', 'age', 'weight'], 
'formats' : ['S32', 'i', 'f']})
a = np.array([('Zhang', 32, 75.5), ('Wang', 24, 65.2)], dtype = PersonalType)
a

array([(b'Zhang', 32, 75.5), (b'Wang', 24, 65.19999694824219)], 
      dtype=[('name', 'S32'), ('age', '<i4'), ('weight', '<f4')])

    S32 :  32个字节的字符串类型  
    i   :  32bit的整数类型，相当于np.int32  
    f   :  32bit的单精度浮点数类型，相当于np.float32

    通过改变a[0]中的字段可以改变原始数组中的字段

## 矩阵运算

* 使用matrix类创建矩阵

In [27]:
import numpy as np
a = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

* dot函数

       对于两个一维的数组，计算的是这两个数组对应下标元素的乘积和(数学上称之为内积)  
       对于二维数组，计算的是两个数组的矩阵乘积  
       对于多维数组，它的通用计算公式如下，即结果数组中的每个元素都是：数组a的最后一维上的所有元素与数组b的倒数第二位上的所有元素的乘积和

In [31]:
import numpy as np
a = np.random.randint(0, 10, size=(3,4))
b = np.random.randint(10, 20, size=(4,3))
a@b  # 这里的@和dot函数等价

array([[172, 181, 128],
       [281, 290, 255],
       [223, 231, 188]])

* 矩阵加减法

In [32]:
import numpy as np
a = np.random.randint(0, 10, size=(3,4))
b = np.random.randint(10, 20, size=(3,4))
print(a+b)
print(a-b)

[[15 26 16 18]
 [22 23 19 22]
 [16 16 26 13]]
[[-15  -8  -4 -14]
 [-10  -9  -7  -6]
 [ -4  -6 -12 -13]]


* 矩阵中更高级的一些运算可以在NumPy的线性代数子库linalg中找到。例如inv函数计算逆矩阵，solve函数可以求解多元一次方程组。